= Kotlin benchmark array to list

Looking at Kotlin source code of `Array.toList()`, `Array.take(n: Int)` and `Array.takeLast(n: Int)`, methods, one can see that they all use a loop to copy elements from the array to the target list.

At least on the JVM, there should be more efficient solutions based on `System.arrayCopy`.

This project compares the standard library method with alternative methods based on direct array copies.

For `toList()` method, we try the following alternatives:

 * `listOf(*array)`
 * `array.copyOf().asList()`

Both methods copy initial array, but, contrary to std implementations, they return a fixed-sized list, where elements can only be replaced.
Although it better match the `toList` semantic, it could break usages where users rely on the output list being fully mutable.

Benchmark results tend to show that both alternate methods have similar performance, and both appear approximately twice as fast as current implementation.

For `take(n)` and `takeLast(n)` methods. we try to replace the loop with `copyOfRange`. There again, the results show that the new method is approximately twice as fast.

== Run the benchmarks

You can launch all benchmarks at once using `./gradlew benchmark`.

[WARNING]
====
It takes a lot of time and uses a lot of CPU
====

Alternatively, individual benchmarks have been designed for specific use cases:

* Target platforms are defined in `${platform}Benchmark` source sets.
  Therefore, you can launch benchmarks for a specific platform using `./gradlew ${PLATFORM}BenchmarkBenchmark`. Example to launch benchmarks on the JVM only: `./gradlew jvmBenchmarkBenchmark`
* Individual configurations have been setup to launch a benchmark for a specific use-case.
  Some examples are `./gradlew flattenBenchmark`, `./gradlew takeWhileBigSizeBenchmark`.
  For a complete list of available use-cases, see *benchmark* -> *configurations* section in link:build.gradle.kts[project build file].

The task will run the benchmark, print a human-readable in standard output, and save a Json report in link:build/reports/benchmarks/[] directory.

It contains JSON reports that can be imported on https://jmh.morethan.io[] website to plot the results.


== Project structure

* Benchmarks are defined in link:src/benchmark/kotlin/[]
* Alternative methods used in benchmarks are defined in link:src/main/kotlin/[]
* Alternative methods are tested in link:src/test/kotlin/[]
